<?php
/**
 * Created by PhpStorm.
 * User: Práce
 * Date: 03.10.2016
 * Time: 15:13
 */

namespace krekos\SlackMessenger;


use Nette\DI\CompilerExtension;

class SlackExtension extends CompilerExtension{
	
	private $defaults = [
		'timeout' => 30,
		'messageFactory' => MessageFactory::class,
		'name' => NULL,
		'title' => NULL,
		'text' => NULL,
		'color' => NULL,
		'channel' => NULL,
		'icon' => NULL,
		'logger'=>[
			'name' => NULL,
			'title' => NULL,
			'text' => NULL,
			'color' => NULL,
			'channel' => NULL,
			'icon' => NULL,
		],
		'messenger' => [
			'name' => NULL,
			'title' => NULL,
			'text' => NULL,
			'color' => NULL,
			'channel' => NULL,
			'icon' => NULL,
		]
	];
	
	public function loadConfiguration(){
		parent::loadConfiguration(); // TODO: Change the autogenerated stub
	}
	
	public function afterCompile(Nette\PhpGenerator\ClassType $class){
		parent::afterCompile($class); // TODO: Change the autogenerated stub
	}
}